---
ID: "4480abc9-5951-4588-ad1c-1cdb0f1a7c0b"
Parent: "1b7f45c3-97b9-4670-9ccd-b009673c8085"
Template: "1b7f45c3-97b9-4670-9ccd-b009673c8085"
Path: /sitecore/templates/Feature/Button/Option List/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191029T104758Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
