---
ID: "d4ba0fba-62b3-41a7-8d88-30fc020be6e1"
Parent: "8ee23890-e1dc-4a37-bd22-c951aba14f51"
Template: "8ee23890-e1dc-4a37-bd22-c951aba14f51"
Path: /sitecore/templates/Feature/Button/Option List/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191023T095058Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
